### ISSUE TITLE
Pedido de dados

### ISSUE THREAD

**Issue by jplimagomes** [guimasuko/project#3]
Quero um csv com a cotação de fechamento do dólar da B3 desde 01-01-2007

**Comment by guimasuko** [comment]
Para acessar os dados pelo Google Drive: https://drive.google.com/file/d/1-0bV3QmA79hIBaDmSx0inGeHarYsW599/view?usp=sharin
Para download dos dados: [dollar_ibov.csv](https://github.com/guimasuko/project/files/8064195/dollar_ibov.csv)

**Comment by jplimagomes** [comment]
Valeu, obrigado! Eram os dados que eu precisava.
